version: "3.7"
services:
    influxdb:
      image: influxdb
      ports:
        - "8086:8086"
      volumes:
        - influxdb:/var/lib/influxdb
    dashboard:
      image: grafana/grafana
      # links:
      #   - sensor
      ports:
        - "3000:3000"
      volumes:
        - grafana:/var/lib/grafana
    
    sensor:
  # use your username instead of mine below!
      image: gaior/rundb:v1.0-X86_64
      links:
        - influxdb
        - dashboard
      volumes:
        - type: bind
          source: /Users/gaior/DAMIC/code/monitoring/testdata
          target: /data
    
volumes:
    influxdb:
    grafana: